# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('lab_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
