# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('company_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('positions', models.IntegerField()),
                ('skills', models.CharField(max_length=500)),
                ('stipend', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Company')),
            ],
        ),
    ]
