# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
