# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_picture', models.FileField(upload_to='')),
                ('mentor', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
